name: SwiftLint

on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
      # - name: GitHub Action for SwiftLint with --strict
      #   uses: norio-nomura/action-swiftlint@3.2.1
      #   with:
      #     args: --strict
      # - name: GitHub Action for SwiftLint (Only files changed in the PR)
      #   uses: norio-nomura/action-swiftlint@3.2.1
      #   env:
      #     DIFF_BASE: ${{ github.base_ref }}
      # - name: GitHub Action for SwiftLint (Different working directory)
      #   uses: norio-nomura/action-swiftlint@3.2.1
      #   env:
      #     WORKING_DIRECTORY: Source


name: PR lint

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: seferov/pr-lint-action@master
      with:
        title-regex: '^\[PROJECT-\d*\](\ )'
        title-regex-flags: 'g' # optional
        error-message: 'Add Jira ID to your title' # optional